### ISSUE TITLE
Examples do not work

### ISSUE THREAD

**Issue by InfamousPlatypus** [hkhetawat/QArithmetic#9]
Windows 10, Python 3.9, Visual Studio I get the error "invalid syntax (QArithmetic.py, line 1)" on any math example in the folder.
It appears to be an issue with "../ QArithmetic.py" not acting as intended.

I don't know if this will be useful
`Stack trace:
 >  File "PathToRepo\QArithmetic\examples\test_add.py", line 4, in <module> (Current frame)
 >    from QArithmetic import add
Loaded '__main__'
Loaded 'runpy'
The program 'python.exe' has exited with code 0 (0x0).`

**Comment by thomasgwong** [comment]
In the examples folder, QArtihmetic.py and qft.py are symlinks to the actual files in the main folder. In Windows, git should be installed with symlink support, and the project should be cloned using `git clone -c core.symlinks=true <URL>`.
